# This rule is not used by the project condenser itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to siphon.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: condenser
    app.kubernetes.io/managed-by: kustomize
  name: siphon-viewer-role
rules:
- apiGroups:
  - siphon.my.domain
  resources:
  - siphons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - siphon.my.domain
  resources:
  - siphons/status
  verbs:
  - get
