# This rule is not used by the project condenser itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over siphon.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: condenser
    app.kubernetes.io/managed-by: kustomize
  name: siphon-admin-role
rules:
- apiGroups:
  - siphon.my.domain
  resources:
  - siphons
  verbs:
  - '*'
- apiGroups:
  - siphon.my.domain
  resources:
  - siphons/status
  verbs:
  - get
