import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { BreadCrumb } from "@/components/layout/Breadcrumb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Siphon</title>
      </head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body>

        <div data-theme="light" className="flex-col h-screen stripe">
          <div className="flex">
            <div className="flex-1 ">
              <Header title="Siphon"></Header>
              <div className="flex flex-1">
                <div className="flex-1 p-6">
                  <div>
                    <h1 className="text-5xl font-extrabold mb-4">🏗️ Workloads</h1>
                    <BreadCrumb />
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
